- name: Ask to proceed with VSCode installation
  pause:
    prompt: Do you want to install Visual Studio Code? (y/n)
  register: vscode_install_response

- name: Set VSCode installation flag
  set_fact:
    install_vscode: "{{ vscode_install_response.user_input | default('n') | lower == 'y' }}"

- name: Ask to proceed with VSCode extensions installation
  pause:
    prompt: Do you want to install extensions for Visual Studio Code? (y/n)
  register: vscode_extensions_response

- name: Set VSCode extensions installation flag
  set_fact:
    install_vscode_extensions: "{{ vscode_extensions_response.user_input | default('n') | lower == 'y' }}"

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - wget
      - gpg
    state: present
  become: true
  when: install_vscode

- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  when: install_vscode

- name: Add VSCode repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  become: true
  when: install_vscode

- name: Update apt cache
  apt:
    update_cache: true
  become: true
  when: install_vscode

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
  become: true
  when: install_vscode

- name: Check if 'code' command is available
  command: which code
  register: code_command
  changed_when: false
  failed_when: code_command.rc != 0
  when: install_vscode_extensions

- name: Install VSCode extensions
  command: code --install-extension {{ item }} --force
  with_items: "{{ vscode_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
  failed_when:
    - vscode_result.rc != 0
    - "'already installed' not in vscode_result.stdout"
  ignore_errors: true
  when: code_command is defined and install_vscode_extensions
