- name: Check if NVIDIA driver is installed
  command: nvidia-smi
  register: nvidia_smi_result
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Get installed NVIDIA driver version
  shell: nvidia-smi --query-gpu=driver_version --format=csv,noheader | cut -d'.' -f1
  register: nvidia_installed_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  when: nvidia_smi_result.rc == 0

- name: Display installed NVIDIA driver version
  debug:
    msg: "Current NVIDIA driver version: {{ nvidia_installed_version.stdout }}"
  when: nvidia_smi_result.rc == 0

- name: Check if installed driver version meets minimum requirements
  fail:
    msg: Current NVIDIA driver version {{ nvidia_installed_version.stdout }} is less than minimum required version {{ min_nvidia_driver_version }}. Please update your driver.
  when:
    - nvidia_smi_result.rc == 0
    - nvidia_installed_version.stdout | int < min_nvidia_driver_version | int

- name: Notify that installed driver meets minimum requirements
  debug:
    msg: Current NVIDIA driver version {{ nvidia_installed_version.stdout }} meets minimum requirements ({{ min_nvidia_driver_version }}).
  when:
    - nvidia_smi_result.rc == 0
    - nvidia_installed_version.stdout | int >= min_nvidia_driver_version | int

- name: Set driver installation flag based on defaults
  set_fact:
    proceed_with_driver_install: true
  when: nvidia_smi_result.rc != 0

- name: Ask to proceed with NVIDIA driver installation (only if interactive mode)
  pause:
    prompt: No NVIDIA driver detected. Do you want to install NVIDIA driver version {{ nvidia_driver_version }}? (y/n)
  register: driver_install_response
  when:
    - nvidia_smi_result.rc != 0
    - ansible_connection != 'local' or lookup('env', 'CI') != 'true'

- name: Override driver installation flag based on user input
  set_fact:
    proceed_with_driver_install: "{{ driver_install_response.user_input | default('y') | lower == 'y' }}"
  when:
    - nvidia_smi_result.rc != 0
    - driver_install_response is defined and driver_install_response.user_input is defined

- name: Update apt cache
  apt:
    update_cache: true
  become: true
  when: nvidia_smi_result.rc != 0 and proceed_with_driver_install

- name: Install prerequisites
  apt:
    name:
      - software-properties-common
      - build-essential
      - dkms
    state: present
  become: true
  when: nvidia_smi_result.rc != 0 and proceed_with_driver_install

- name: Add NVIDIA driver repository
  apt_repository:
    repo: "{{ nvidia_driver_ubuntu_repository }}"
    state: present
  become: true
  when: nvidia_smi_result.rc != 0 and proceed_with_driver_install

- name: Update apt cache after adding repository
  apt:
    update_cache: true
  become: true
  when: nvidia_smi_result.rc != 0 and proceed_with_driver_install

- name: Install NVIDIA driver
  apt:
    name: nvidia-driver-{{ nvidia_driver_version }}
    state: present
  become: true
  when: nvidia_smi_result.rc != 0 and proceed_with_driver_install

- name: Display installation completion message
  debug:
    msg: NVIDIA driver installation completed. A system reboot is recommended.
  when: nvidia_smi_result.rc != 0 and proceed_with_driver_install
